### ISSUE TITLE
能否制作成基于node的打印服务接口,而不是基于electron,因为服务器绝大数是server版

### ISSUE THREAD

**Issue by LTAND** [CcSimple/electron-hiprint#10]

**Comment by Xavier9896** [comment]
emmm……可以用node做过服务器的中转服务

**Comment by Xavier9896** [comment]
#11 
https://github.com/Xavier9896/node-hiprint-transit

**Comment by LTAND** [comment]
> #11 https://github.com/Xavier9896/node-hiprint-transit

node-hiprint-transit使用这个,还是得安装electron-hiprint, 如果服务端node只接收pdf文件使用unix-print库打印,用ipp库获取打印机列表,是不是就不需要安装electron

**Comment by Xavier9896** [comment]
是的，的确可以用 unix-print 来实现 linux 上的 pdf 打印，但是打印机不应该直接连接到服务器，打印机应该连接到末梢终端，而不是服务器。

**Comment by jinpy666** [comment]
是的，只有Windows有连接打印机的能力，解决驱动什么的
