### ISSUE TITLE
托盘右键设置的弹窗，设置只要关闭（无论是×还是底部按钮），再打开设置都会报错

### ISSUE THREAD

**Issue by breezeyyy** [CcSimple/electron-hiprint#14]
![image](https://github.com/CcSimple/electron-hiprint/assets/48956444/1ca5a1dd-3e9d-4ae2-9bca-de8f842530a4)

**Comment by breezeyyy** [comment]
也不对，设置只要关闭（无论是×还是底部按钮），再打开设置都会报错

**Comment by Xavier9896** [comment]
#15 已提交 pr 等待合并解决
